import { education } from '@/types/education'

export const EDUCATIONS: education[] = [
   {
      title: 'ed-title-1',
      institution: 'ed-institution-1',
      img: 'title',
      alt: 'Imagen del titulo de tecnico superior un desarrollo del software.',
      url: undefined,
      linkText: undefined,
   },
   {
      title: 'ed-title-2',
      institution: 'ed-institution-2',
      img: 'powerbi-avanzado',
      alt: '',
      url: 'https://youtube.com/playlist?list=PL2Z95CSZ1N4HjIHxZjiTee21X_m1IzmUq&si=8t0JqIGm7rHWAddN',
      linkText: undefined,
   },
   {
      title: 'ed-title-10',
      institution: 'ed-institution-10',
      img: 'powerbi-intro',
      alt: '',
      url: 'https://m.youtube.com/playlist?list=PL2Z95CSZ1N4Hhlv70xz0tdr9od6w_PMTX',
      linkText: undefined,
   },
   {
      title: 'ed-title-3',
      institution: 'ed-institution-3',
      img: '',
      alt: '',
      url: '',
      linkText: undefined,
   },
   {
      title: 'ed-title-4',
      institution: 'ed-institution-4',
      img: 'sql-server',
      alt: '',
      url: 'https://www.udemy.com/course/aprende-sql-server-desde-cero-crea-tu-propia-base-de-datos',
      linkText: undefined,
   },
   {
      title: 'ed-title-5',
      institution: 'ed-institution-5',
      img: '',
      alt: '',
      url: '',
      linkText: undefined,
   },
   {
      title: 'ed-title-6',
      institution: 'ed-institution-6',
      img: 'c-shart',
      alt: '',
      url: 'https://www.udemy.com/course/curso-de-c-sharp-net-core-desde-cero/learn/lecture/14653400?start=0#content',
      linkText: undefined,
   },
   {
      title: 'ed-title-7',
      institution: 'ed-institution-7',
      img: '',
      alt: '',
      url: '',
      linkText: undefined,
   },
   {
      title: 'ed-title-8',
      institution: 'ed-institution-8',
      img: 'istqb',
      alt: '',
      url: 'https://www.istqb.org/',
      linkText: undefined,
   },
   {
      title: 'ed-title-9',
      institution: 'ed-institution-9',
      img: '',
      alt: '',
      url: '',
      linkText: undefined,
   },
];